//

export const nameDrug = [
  { name: 'Adenozyna' },
  { name: 'Adenocor' },
  { name: 'Adrenalina' },
  { name: 'Amiodaron' },
  { name: 'Amiokordin' },
  { name: 'Cordarone' },
  { name: 'Artopina' },
  { name: 'Atropinum' },
  { name: 'Budesonidum' },
  { name: 'Budixon' },
  { name: 'Nebbud' },
  { name: 'Benodil' },
  { name: 'Captopril' },
  { name: 'Clemastinum' },
  { name: 'Klopidogrel' },
  { name: 'Plavix' },
  { name: 'Areplex' },
  { name: 'Deksametazon' },
  { name: 'Dexaven' },
  { name: 'Dexamethason' },
  { name: 'Diazepamum' },
  { name: 'Relanium' },
  { name: 'Relsed' },
  { name: 'Relsed' },
  { name: 'Valium' },
  { name: 'Drotaweryna' },
  { name: 'No-Spa' },
  { name: 'DrotaFeme' },
  { name: 'Metafen' },
  { name: 'Fentanyl' },
  { name: 'Flumazenil' },
  { name: 'Furosemidum' },
  { name: 'Glukagon' },
  { name: 'Glukoza20%' },
  { name: 'Glucosum20%' },
  { name: 'Heparyna' },
  { name: 'Heparin' },
  { name: 'Hydrokortyzon' },
  { name: 'Corhydron' },
  { name: 'Hydroksyzyna' },
  { name: 'Hydroxyzinum' },
  { name: 'Ibuprofen' },
  { name: 'Ibuprom' },
  { name: 'Metafen' },
  { name: 'Nurofen' },
  { name: 'Izosorbid' },
  { name: 'Mononit' },
  { name: 'Effox' },
  { name: 'Ketoprofen' },
  { name: 'Ketonal' },
  { name: 'Ketokaps' },
  { name: 'Refastin' },
  { name: 'Kwas acetylosalicylowy' },
  { name: 'Aspirin' },
  { name: 'Polopiryna S' },
  { name: 'Kwas Traneksamowy' },
  { name: 'Exacyl' },
  { name: 'Lidokaina' },
  { name: 'Lignocainu' },
  { name: 'Lignocainu żel' },
  { name: 'Magnez' },
  { name: 'Mannitol 15%' },
  { name: 'Metamizol' },
  { name: 'Pyralgina' },
  { name: 'Metoklopramid' },
  { name: 'Metoclopramidum' },
  { name: 'Metoprolol' },
  { name: 'Midazolam' },
  { name: 'Midanium' },
  { name: 'Dormicum' },
  { name: 'Sopodorm' },
  { name: 'Morfina' },
  { name: 'Morphini' },
  { name: 'Nalokson' },
  { name: 'Naloxonum' },
  { name: 'Natrii hydrogenocarbonas8,4%' },
  { name: 'Nitrogliceryna' },
  { name: 'Nitromint' },
  { name: 'Noradrenalina' },
  { name: 'Papaweryna' },
  { name: 'Papaverinum' },
  { name: 'Paracetamol' },
  { name: 'APAP' },
  { name: 'Prasugrel' },
  { name: 'Bewim' },
  { name: 'Efient' },
  { name: 'Salbutamol' },
  { name: 'Ventolin' },
  { name: 'Thiethylperazinum' },
  { name: 'Torecan' },
  { name: 'Tikagrelor' },
  { name: 'Ticagrelor' },
  { name: 'Brilque' },
  { name: 'Urapidil' },
  { name: 'Ebrantil' },
  { name: 'Tlen' },
];
export const unitOfMeasure = [
  { name: 'g' },
  { name: 'mg' },
  { name: 'µg' },
  { name: 'ml' },
];

export const unit = [
  {
    short: 'i.m.',
    name: 'i.m. - domięśniowo',
  },
  {
    short: 'i.o.',
    name: 'i.o. - doszpikowo',
  },
  {
    short: 'i.v.',
    name: 'i.v. - dożylnie',
  },
  {
    short: 'p.o.',
    name: 'p.o. - doustnie',
  },
  {
    short: 'p.r.',
    name: 'p.r. - doodbytniczo',
  },
  {
    short: 'i.c.',
    name: 'i.c. - śródskórnie',
  },
  {
    short: 's.c.',
    name: 's.c. - podskórnie',
  },
  {
    short: 's.l.',
    name: 's.l. - podjęzykowo',
  },
  {
    short: 'e.t.',
    name: 'e.t. - dotchawiczo',
  },
  {
    short: 'inhalatio',
    name: 'wziewnie',
  },
  {
    short: 'p.v.',
    name: 'p.v. - dopochwowo',
  },
  {
    short: 'i.a.',
    name: 'i.a. - dotętniczo',
  },
  {
    short: 'i.a.c.',
    name: 'i.a.c. - dowieńcowo',
  },
  {
    short: 'i.n.',
    name: 'i.n. - donosowo',
  },
];
